const router = require("express").Router();
const auth   = require("../middleware/auth");
const { Note } = require("../models/index");
const PDFDocument = require("pdfkit");

router.get("/notes/:id", auth, async (req, res) => {
  try {
    const note = await Note.findOne({ _id: req.params.id, user: req.user.id });
    if (!note) return res.status(404).json({ error: "Note not found" });

    const doc = new PDFDocument({ margin: 50, size: "A4" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${note.title.replace(/[^a-z0-9]/gi,"_")}.pdf"`);
    doc.pipe(res);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill("#0f172a");
    doc.fillColor("#4ade80").fontSize(22).font("Helvetica-Bold").text("EnggStack", 50, 20);
    doc.fillColor("#888").fontSize(10).font("Helvetica").text("Study Notes Export", 50, 48);
    doc.moveDown(2);

    // Title
    doc.fillColor("#1e293b").fontSize(20).font("Helvetica-Bold").text(note.title, 50, 100);
    if (note.subject) doc.fillColor("#4ade80").fontSize(12).font("Helvetica").text(`Subject: ${note.subject}`, 50, 128);
    doc.fillColor("#666").fontSize(10).text(`Created: ${new Date(note.createdAt).toLocaleDateString("en-IN")} · Updated: ${new Date(note.updatedAt).toLocaleDateString("en-IN")}`, 50, 145);
    doc.moveTo(50,165).lineTo(545,165).stroke("#e2e8f0");
    doc.moveDown(1);

    // Content
    doc.fillColor("#1e293b").fontSize(12).font("Helvetica").text(note.content || "(empty)", 50, 180, { lineGap: 6, width: 495 });

    // Footer
    doc.fillColor("#ccc").fontSize(9).text(`Generated by EnggStack • ${new Date().toLocaleString()}`, 50, doc.page.height - 40, { align: "center", width: 495 });

    doc.end();
  } catch (e) { res.status(500).json({ error: e.message }); }
});

router.get("/notes-all", auth, async (req, res) => {
  try {
    const notes = await Note.find({ user: req.user.id }).sort({ updatedAt: -1 });
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=EnggStack_All_Notes.pdf");
    doc.pipe(res);

    doc.rect(0,0,doc.page.width,80).fill("#0f172a");
    doc.fillColor("#4ade80").fontSize(24).font("Helvetica-Bold").text("EnggStack — All Notes", 50, 24);
    doc.fillColor("#888").fontSize(10).font("Helvetica").text(`${notes.length} notes exported on ${new Date().toLocaleDateString()}`, 50, 52);

    notes.forEach((note, i) => {
      if (i > 0) doc.addPage();
      else doc.moveDown(3);
      doc.fillColor("#1e293b").fontSize(18).font("Helvetica-Bold").text(note.title);
      if (note.subject) doc.fillColor("#4ade80").fontSize(11).font("Helvetica").text(`Subject: ${note.subject}`);
      doc.fillColor("#999").fontSize(9).text(`Updated: ${new Date(note.updatedAt).toLocaleDateString()}`);
      doc.moveTo(50, doc.y+5).lineTo(545, doc.y+5).stroke("#e2e8f0");
      doc.moveDown(0.5);
      doc.fillColor("#1e293b").fontSize(11).font("Helvetica").text(note.content||"(empty)", { lineGap:4, width:495 });
    });

    doc.end();
  } catch (e) { res.status(500).json({ error: e.message }); }
});

module.exports = router;
