<<<<<<< HEAD
const router   = require("express").Router();
const jwt      = require("jsonwebtoken");
const { Note } = require("../models/index");
const PDFDocument = require("pdfkit");

// Token can come from Authorization header OR ?token= query param
function getUser(req) {
  const header = req.headers.authorization;
  const query  = req.query.token;
  const token  = header?.startsWith("Bearer ") ? header.slice(7) : (header || query);
  if (!token) return null;
  try { return jwt.verify(token, process.env.JWT_SECRET); } catch { return null; }
}

function buildPDF(doc, title, subject, content, createdAt, updatedAt) {
  // Dark header bar
  doc.rect(0, 0, doc.page.width, 72).fill("#0f172a");
  doc.fillColor("#4ade80").fontSize(20).font("Helvetica-Bold").text("EnggStack", 50, 18);
  doc.fillColor("#888").fontSize(10).font("Helvetica").text("Study Notes", 50, 44);

  // Title block
  doc.fillColor("#1e293b").fontSize(20).font("Helvetica-Bold").text(title, 50, 90);
  if (subject) doc.fillColor("#4ade80").fontSize(12).font("Helvetica").text(`Subject: ${subject}`, 50, 116);
  doc.fillColor("#666").fontSize(9)
    .text(`Created: ${new Date(createdAt).toLocaleDateString("en-IN")}  ·  Updated: ${new Date(updatedAt).toLocaleDateString("en-IN")}`, 50, subject ? 132 : 116);

  const bodyTop = subject ? 156 : 140;
  doc.moveTo(50, bodyTop - 6).lineTo(545, bodyTop - 6).strokeColor("#e2e8f0").stroke();
  doc.fillColor("#1e293b").fontSize(12).font("Helvetica")
    .text(content || "(empty note)", 50, bodyTop, { lineGap: 5, width: 495 });

  // Footer
  doc.fillColor("#ccc").fontSize(8)
    .text(`Generated by EnggStack · ${new Date().toLocaleString()}`, 50, doc.page.height - 36, { align: "center", width: 495 });
}

// Export single note
router.get("/notes/:id", async (req, res) => {
  try {
    const user = getUser(req);
    if (!user) return res.status(401).json({ error: "Unauthorized" });

    const note = await Note.findOne({ _id: req.params.id, user: user.id });
    if (!note) return res.status(404).json({ error: "Note not found" });

    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const filename = note.title.replace(/[^a-z0-9]/gi, "_").slice(0, 60);
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}.pdf"`);
    doc.pipe(res);
    buildPDF(doc, note.title, note.subject, note.content, note.createdAt, note.updatedAt);
=======
const router = require("express").Router();
const auth   = require("../middleware/auth");
const { Note } = require("../models/index");
const PDFDocument = require("pdfkit");

router.get("/notes/:id", auth, async (req, res) => {
  try {
    const note = await Note.findOne({ _id: req.params.id, user: req.user.id });
    if (!note) return res.status(404).json({ error: "Note not found" });

    const doc = new PDFDocument({ margin: 50, size: "A4" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${note.title.replace(/[^a-z0-9]/gi,"_")}.pdf"`);
    doc.pipe(res);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill("#0f172a");
    doc.fillColor("#4ade80").fontSize(22).font("Helvetica-Bold").text("EnggStack", 50, 20);
    doc.fillColor("#888").fontSize(10).font("Helvetica").text("Study Notes Export", 50, 48);
    doc.moveDown(2);

    // Title
    doc.fillColor("#1e293b").fontSize(20).font("Helvetica-Bold").text(note.title, 50, 100);
    if (note.subject) doc.fillColor("#4ade80").fontSize(12).font("Helvetica").text(`Subject: ${note.subject}`, 50, 128);
    doc.fillColor("#666").fontSize(10).text(`Created: ${new Date(note.createdAt).toLocaleDateString("en-IN")} · Updated: ${new Date(note.updatedAt).toLocaleDateString("en-IN")}`, 50, 145);
    doc.moveTo(50,165).lineTo(545,165).stroke("#e2e8f0");
    doc.moveDown(1);

    // Content
    doc.fillColor("#1e293b").fontSize(12).font("Helvetica").text(note.content || "(empty)", 50, 180, { lineGap: 6, width: 495 });

    // Footer
    doc.fillColor("#ccc").fontSize(9).text(`Generated by EnggStack • ${new Date().toLocaleString()}`, 50, doc.page.height - 40, { align: "center", width: 495 });

>>>>>>> aa34717e4aab2e0d5daa253fdebdafcf824aa76c
    doc.end();
  } catch (e) { res.status(500).json({ error: e.message }); }
});

<<<<<<< HEAD
// Export all notes
router.get("/notes-all", async (req, res) => {
  try {
    const user = getUser(req);
    if (!user) return res.status(401).json({ error: "Unauthorized" });

    const notes = await Note.find({ user: user.id }).sort({ updatedAt: -1 });
=======
router.get("/notes-all", auth, async (req, res) => {
  try {
    const notes = await Note.find({ user: req.user.id }).sort({ updatedAt: -1 });
>>>>>>> aa34717e4aab2e0d5daa253fdebdafcf824aa76c
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=EnggStack_All_Notes.pdf");
    doc.pipe(res);

<<<<<<< HEAD
    // Cover page
    doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0f172a");
    doc.fillColor("#4ade80").fontSize(36).font("Helvetica-Bold").text("EnggStack", 50, 200, { align: "center" });
    doc.fillColor("#888").fontSize(16).font("Helvetica").text("All Notes Export", 50, 250, { align: "center" });
    doc.fillColor("#444").fontSize(12).text(`${notes.length} notes · ${new Date().toLocaleDateString("en-IN")}`, 50, 290, { align: "center" });

    notes.forEach((note, i) => {
      doc.addPage();
      buildPDF(doc, note.title, note.subject, note.content, note.createdAt, note.updatedAt);
=======
    doc.rect(0,0,doc.page.width,80).fill("#0f172a");
    doc.fillColor("#4ade80").fontSize(24).font("Helvetica-Bold").text("EnggStack — All Notes", 50, 24);
    doc.fillColor("#888").fontSize(10).font("Helvetica").text(`${notes.length} notes exported on ${new Date().toLocaleDateString()}`, 50, 52);

    notes.forEach((note, i) => {
      if (i > 0) doc.addPage();
      else doc.moveDown(3);
      doc.fillColor("#1e293b").fontSize(18).font("Helvetica-Bold").text(note.title);
      if (note.subject) doc.fillColor("#4ade80").fontSize(11).font("Helvetica").text(`Subject: ${note.subject}`);
      doc.fillColor("#999").fontSize(9).text(`Updated: ${new Date(note.updatedAt).toLocaleDateString()}`);
      doc.moveTo(50, doc.y+5).lineTo(545, doc.y+5).stroke("#e2e8f0");
      doc.moveDown(0.5);
      doc.fillColor("#1e293b").fontSize(11).font("Helvetica").text(note.content||"(empty)", { lineGap:4, width:495 });
>>>>>>> aa34717e4aab2e0d5daa253fdebdafcf824aa76c
    });

    doc.end();
  } catch (e) { res.status(500).json({ error: e.message }); }
});

module.exports = router;
