const router   = require("express").Router();
const jwt      = require("jsonwebtoken");
const { Note } = require("../models/index");
const PDFDocument = require("pdfkit");

// Token can come from Authorization header OR ?token= query param
function getUser(req) {
  const header = req.headers.authorization;
  const query  = req.query.token;
  const token  = header?.startsWith("Bearer ") ? header.slice(7) : (header || query);
  if (!token) return null;
  try { return jwt.verify(token, process.env.JWT_SECRET); } catch { return null; }
}

function buildPDF(doc, title, subject, content, createdAt, updatedAt) {
  // Dark header bar
  doc.rect(0, 0, doc.page.width, 72).fill("#0f172a");
  doc.fillColor("#4ade80").fontSize(20).font("Helvetica-Bold").text("EnggStack", 50, 18);
  doc.fillColor("#888").fontSize(10).font("Helvetica").text("Study Notes", 50, 44);

  // Title block
  doc.fillColor("#1e293b").fontSize(20).font("Helvetica-Bold").text(title, 50, 90);
  if (subject) doc.fillColor("#4ade80").fontSize(12).font("Helvetica").text(`Subject: ${subject}`, 50, 116);
  doc.fillColor("#666").fontSize(9)
    .text(`Created: ${new Date(createdAt).toLocaleDateString("en-IN")}  ·  Updated: ${new Date(updatedAt).toLocaleDateString("en-IN")}`, 50, subject ? 132 : 116);

  const bodyTop = subject ? 156 : 140;
  doc.moveTo(50, bodyTop - 6).lineTo(545, bodyTop - 6).strokeColor("#e2e8f0").stroke();
  doc.fillColor("#1e293b").fontSize(12).font("Helvetica")
    .text(content || "(empty note)", 50, bodyTop, { lineGap: 5, width: 495 });

  // Footer
  doc.fillColor("#ccc").fontSize(8)
    .text(`Generated by EnggStack · ${new Date().toLocaleString()}`, 50, doc.page.height - 36, { align: "center", width: 495 });
}

// Export single note
router.get("/notes/:id", async (req, res) => {
  try {
    const user = getUser(req);
    if (!user) return res.status(401).json({ error: "Unauthorized" });

    const note = await Note.findOne({ _id: req.params.id, user: user.id });
    if (!note) return res.status(404).json({ error: "Note not found" });

    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const filename = note.title.replace(/[^a-z0-9]/gi, "_").slice(0, 60);
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}.pdf"`);
    doc.pipe(res);
    buildPDF(doc, note.title, note.subject, note.content, note.createdAt, note.updatedAt);
    doc.end();
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// Export all notes
router.get("/notes-all", async (req, res) => {
  try {
    const user = getUser(req);
    if (!user) return res.status(401).json({ error: "Unauthorized" });

    const notes = await Note.find({ user: user.id }).sort({ updatedAt: -1 });
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=EnggStack_All_Notes.pdf");
    doc.pipe(res);

    // Cover page
    doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0f172a");
    doc.fillColor("#4ade80").fontSize(36).font("Helvetica-Bold").text("EnggStack", 50, 200, { align: "center" });
    doc.fillColor("#888").fontSize(16).font("Helvetica").text("All Notes Export", 50, 250, { align: "center" });
    doc.fillColor("#444").fontSize(12).text(`${notes.length} notes · ${new Date().toLocaleDateString("en-IN")}`, 50, 290, { align: "center" });

    notes.forEach((note, i) => {
      doc.addPage();
      buildPDF(doc, note.title, note.subject, note.content, note.createdAt, note.updatedAt);
    });

    doc.end();
  } catch (e) { res.status(500).json({ error: e.message }); }
});

module.exports = router;
